export const transactionForm = {
    id: 0,
    quantity: 0,
    number: "",
    tax: "",
    orderPrice: null,
    totalPrice: null,
    totalDiscount: null,
    employeeId: 0,
    createdAt: "",
    updatedAt: "",
    deletedAt: "",
    cakeVariantId: 0,
    orders: [],
  };